title: Hien Nguyen Thi
logo: hienngt.github.io/hiennt.jpg
description: Data Engineer
show_downloads: false
theme: jekyll-theme-minimal
# Sidebar settings
# sidebar: true  
# sidebar-about-description: 
# sidebar-avatar: /hiennt.jpg 
